name: prepare-rtl
description: "Prepare RTL"

inputs:
  tools-version:
    description: Kind of toolchain to build
    required: true
    default: "riscv-tools"
  group-key:
    description: Group to test
    required: true
  build-script:
    description: The script to run
    required: true
  build-type:
    description: The type of build
    required: true

runs:
  using: "includes"

  steps:
    - name: is-riscv-tools
      if: ${{ inputs.tools-version }} == "riscv-tools"
      includes: ./.github/actions/includes/build-riscv-toolchain
    - name: is-esp-tools
      if: ${{ inputs.tools-version }} == "esp-tools"
      includes: ./.github/actions/includes/build-esp-toolchain
    - name: generate key
      id: genkey-build-rtl
      run: |
        echo "::set-output name=cache-dir::~/project"
        echo "::set-output name=cache-key::$${ inputs.group-key }}-${{ github.ref }}-${{ github.sha }}"

    - uses: actions/cache@v2
      id: prepare-rtl-cache
      with:
        path: ${{ steps.genkey-build-rtl.outputs.cache-dir }}
        key: ${{ steps.genkey-build-rtl.outputs.cache-key }}
    - name: build tools-version if not cached
      if: steps.prepare-rtl-cache.outputs.cache-hit != 'true'
      run: ./.github/${{ inputs.build-script }} ${{ inputs.group-key }} ${{ inputs.build-type }}




