name: build-riscv-toolchain
description: "Build the riscv toolchain"

runs:
  using: "includes"

  steps:
    - name: Generate Hashes
      run: .github/scripts/create-hash.sh
    - name: generate key
      id: genkey
      run: |
        echo "::set-output name=cache-key::riscv-tools-installed-${{ env.tools-cache-version }}-$(shasum riscv-tools.hash | cut -d' ' -f1)"
    - uses: actions/cache@v2
      id: riscv-tools-cache
      with:
        path: riscv-tools-install
        key: ${{ steps.genkey.outputs.cache-key }}
    - name: build tools-version if not cached
      if: steps.riscv-tools-cache.outputs.cache-hit != 'true'
      run: ./.github/scripts/build-toolchains.sh riscv-tools


