name: toolchain-build
description: "Build a toolchain"

inputs:
  tools-version:  # id of input
    description: Kind of toolchain to build
    required: true
    default: "riscv-tools"

runs:
  using: "includes"

  steps:
    - name: Create hash of toolchains
      run: sudo chown -R riscvuser . ~riscvuser /github/home
    - name: dog greet step
      run: echo Lickety split ${{ inputs.who-to-greet }}.

