name: chipyard-ci-process

on: [push]

env:
  tools-cache-version: v6

jobs:

  commit-on-master-check:
    name: commit-on-master-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fix permissions
        run: sudo chown -R riscvuser . ~riscvuser /github/home
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commits of each submodle
        run: .github/scripts/check-commit.sh

  tutorial-setup-check:
    name: tutorial-setup-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fix permissions
        run: sudo chown -R riscvuser . ~riscvuser /github/home
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check that the tutorial-setup patches apply
        run: scripts/tutorial-setup.sh

  documentation-check:
    name: documentation-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fix permissions
        run: sudo chown -R riscvuser . ~riscvuser /github/home
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check that documentation builds with no warnings/errors
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          sudo pip3 install -r docs/requirements.txt
          make -C docs html
      - name: Show error log from sphinx if failed
        if: ${{ failure() }}
        run: cat /tmp/sphinx-err*.log


  install-riscv-toolchain:
    name: commit-on-master-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fix permissions
        run: sudo chown -R riscvuser . ~riscvuser /github/home
      - name: Checkout
        uses: actions/checkout@v2
      - name: toolchain build
        includes: ./.github/actions/includes/toolchain-build
        with:
          tools-version: riscv-tools