name: chipyard-ci-process

on: [push]

env:
  tools-cache-version: v9

jobs:
  testing:
    name: install both toolchains
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:1d51bb90
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - includes: ./.github/actions/includes/startup
      - includes: ./.github/actions/includes/testing
        with:
          key: riscv-key-test
