name: chipyard-ci-process

on: [push]

env:
  tools-cache-version: v6

jobs:

  install-riscv-toolchain:
    name: install riscv toolchain
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - includes: ./.github/actions/includes/startup
      - includes: ./.github/actions/includes/toolchain-build
        with:
          tools-version: riscv-tools

  install-esp-toolchain:
    name: install esp toolchain
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - includes: ./.github/actions/includes/startup
      - includes: ./.github/actions/includes/toolchain-build
        with:
          tools-version: esp-tools

  install-both:
    needs: [install-riscv-toolchain, install-esp-toolchain]
    name: install both toolchains
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - includes: ./.github/actions/includes/startup
      - includes: ./.github/actions/includes/toolchain-build
        with:
          tools-version: esp-tools
      - includes: ./.github/actions/includes/toolchain-build
        with:
          tools-version: esp-tools