name: dog action
description: "dog greet someone"

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "includes"

  steps:
    - name: fix permissions
      run: sudo chown -R riscvuser . ~riscvuser /github/home
    - name: dog greet step
      run: echo Lickety split ${{ inputs.who-to-greet }}.

