name: build-extra-tests
description: "Build the extra tests"

runs:
  using: "includes"

  steps:
    - name: Generate Hashes
      run: .github/scripts/create-hash.sh
    - name: generate key
      id: genkey-extra-tests
      run: |
        echo "::set-output name=extra-tests-cache-key::extra-tests-${{ github.ref }}-${{ github.sha }}"
    - uses: actions/cache@v2
      id: extra-tests-cache
      with:
        path: extra-tests-install
        key: ${{ steps.genkey-extra-tests.outputs.cache-key }}
    - name: build tools-version if not cached
      if: steps.extra-tests-cache.outputs.cache-hit != 'true'
      run: .github/scripts/build-extra-tests.sh


