name: install-esp-toochain-sub
description: "Build the esp toolchain"

runs:
  using: "includes"

  steps:
    - name: fix permissions
      run: sudo chown -R riscvuser . ~riscvuser /github/home
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Hashes
      run: .github/scripts/create-hash.sh
    - name: generate key
      id: genkey
      run: |
        echo "::set-output name=cache-key::${{ inputs.tools-version }}
    - uses: actions/cache@v2
      id: esp-tools-cache
      with:
        path: esp-tools-install
        key: riscv-installed-${{ env.tools-cache-version }}-$(shasum esp-tools.hash | cut -d' ' -f1)"
    - name: build esp tools if not cached
      if: steps.esp-tools-cache.outputs.cache-hit != 'true'
      run: ./.github/scripts/build-toolchains.sh ${{ inputs.tools-version }}

#    - name: Create hash of toolchains
#      run: sudo chown -R riscvuser . ~riscvuser /github/home
#    - name: dog greet step
#      run: echo Lickety split ${{ inputs.who-to-greet }}.

