name: 'testing'
description: "Test calling to local system"

inputs:
  my-input:
    description: input
    default: true

outputs:
  my-output:
    description: fox
    value: 66
runs:
  using: "composite"
  steps:
    - name: Hello
      run: echo "Hello world"
      shell: bash
    - name: conditionally run
      if: inputs.my-input
      run: echo "I am a dog"
      shell: bash
    - name: Hello
      run: echo "Bye"
      shell: bash