name: chipyard-ci-process

on: [push]

jobs:
  cache-test:
    name: cache-test
    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: step1
        run: echo step1-${GITHUB_REF}
      - name: mkdir
        run: mkdir -p cache-dir
      - uses: actions/cache@v2
        id: cache-222
        with:
          path: cache-dir
          key: cache-dir-${GITHUB_REF}
          restore-keys: cache-dir-${GITHUB_REF}
      - name: ls the repo
        run: ls -lt cache-dir
      - name: fill file
        if: steps.cache-222.outputs.cache-hit != 'true'
        run: touch cache-dir/cache-me
      - name: check fill
        run: ls -lt cache-dir

  use-cache:
    name: use-cache
    needs: cache-test
    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: step1
        run: echo step1-${GITHUB_REF}
      - uses: actions/cache@v2
        id: cache-222
        with:
          path: cache-dir
          key: cache-dir-${GITHUB_REF}
          restore-keys: cache-dir-${GITHUB_REF}
      - name: check fill
        run: ls -lt cache-dir
