name: chipyard-ci-process

on: [push]

env:
  tools-cache-version: v6

jobs:
  run-as-root:
    name: run as root
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: where am i before checkout
        run: pwd
      - name: Checkout
        uses: actions/checkout@v2
      - name: where am i after checkout
        run: pwd
      - name: who am i
        run: |
          whoami
      - name: where am i before checkout
        run: pwd
      - name: show github paths
        run: |
          ls -la /bithub/home
          ls -la /github/workspace
          ls -la /github/workflo


