name: chipyard-ci-process

on: [push]

jobs:
  cache-test:
    name: cache-test
    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - uses: actions/cache@v2
        id: cache-111
        with:
          path: cache-dir
          key: cache-dir-${{ env.GITHUB_SHA }}
          restore-keys: cache-dir-
      - name: ls the repo
        run: ls -lt cache-dir

  use-cache:
    name: use-cache
    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fill file
        if: steps.cache-111.outputs.cache-hit != 'true'
        run: touch cache-dir/cache-me
      - name: ls
        run: ls -lt cache-dir

#  commit-on-master-check:
#    name: commit-on-master-check
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - name: Hello
#        run: echo =========CHIPYARD CI STARTED=================
#      - name: Dump GitHub context
#        env:
#         GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: fix permissions 1
#        run: sudo chown -R riscvuser .
#      - name: Basics
#        run: whoami && echo pwd `pwd` && ls -la /github ~riscvuser
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: fix permissions 2
#        run: sudo chown -R riscvuser .
#      - name: Check space
#        run: |
#          mkdir -p "/home/riscvuser/riscv-tools"
#          echo ===== df ========
#          df -m
#          echo ===== du . =========
#          df -m .
#          du -s -m .
#          echo ===== du /__w/chipyard/chipyard =========
#          df -m /__w/chipyard/chipyard
#          du -s -m /__w/chipyard/chipyard
#          echo ===== du /home/riscvuser/riscv-tools =========
#          df -m  /home/riscvuser/riscv-tools
#          du -s -m /home/riscvuser/riscv-tools
#          echo ========================
#
#      - name: Banner
#        run: printf "===========Create Hashes\ncwd `pwd`\nuser `whoami`\n`echo homedir ~`\nHOME $HOME\n============="
#      - name: Checkout commits of each submodule
#        run: .github/scripts/check-commit.sh

#  tutorial-set-up-check:
#    name: tutorial-set-up-check
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - uses: actions/checkout@v2
#      - name: fix permissions
#        run: sudo chown -R riscvuser .
#      - name: Check that the tutorial-setup patches apply
#        run: ./scripts/tutorial-setup.sh
#
#  documentation-check:
#    name: tutorial-set-up-check
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - uses: actions/checkout@v2
#      - name: fix permissions
#        run: sudo chown -R riscvuser .
#      - name: Check that documentation builds with no warnings/errors
#        run: |
#            sudo apt-get update -y
#            sudo apt-get install -y python3-pip
#            sudo pip3 install -r docs/requirements.txt
#            make -C docs html
#
#  install-riscv-toolchain:
#    name: install-riscv-toolchain
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#      TOOLS_CACHE_VERSION: v6
#    steps:
#      - name: Hello
#        run: echo =========CHIPYARD CI STARTED=================
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: fix permissions 1
#        run: sudo chown -R riscvuser .
#      - name: Basics
#        run: whoami && echo pwd `pwd` && ls -la /github ~riscvuser
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: fix permissions 2
#        run: sudo chown -R riscvuser .
#      - name: Banner
#        run: echo ======CACHE_VERSION===${{ env.TOOLS_CACHE_VERSION }}
#      - name: Set cache dir if not present
#        run: mkdir -p "/home/riscvuser/riscv-tools"
#      - name: Cache Toolchains
#        id: cache-riscv-tools
#        uses: actions/cache@v2
#        with:
#          path: "/home/riscvuser/riscv-tools"
#          key: riscv-tools-installed-${{ env.TOOLS_CACHE_VERSION }}
#          restore-keys: |
#            riscv-tools-installed-${{ env.TOOLS_CACHE_VERSION }}
#            riscv-tools-installed-
#      - name: building
#        if: steps.cache-riscv-tools.outputs.cache-hit != 'true'
#        run: .github/scripts/build-toolchains.sh riscv-tools
#      - name: Check riscv-tools
#        run: ls -ltr /home/riscvuser/riscv-tools
#
#  build-cache:
#    name: build-cache
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#      TOOLS_CACHE_VERSION: "v6"
#    steps:
#      - uses: actions/checkout@v2
#      - name: fix permissions
#        run: sudo chown -R riscvuser .
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
##      - name: set up cache
##        uses: actions/cache@v2
##        id: chickcache
##        env:
##          cache_name: practice_cache
##        with:
##          path: ./chickdir
##          key: chickdirkey
##          restore-keys: chickdirkey
##      - name: Stuff cache
##        if: steps.chickcache.outputs.cache-hit != 'true'
##        run: mkdir chickdir && echo hellochick > chickdir/chickfile
##      - name: x2
##        run: cat chickdir/chickfile
#
#
#
#
#
#
