name: chipyard-ci-process

on: [push]

jobs:
  commit-on-master-check:
    name: commit-on-master-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-image:1.0.1
      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - uses: actions/checkout@v2
      - name: fix permissions
        run: sudo chown -R riscvuser .
      - name: Banner
        run: printf "===========Create Hashes\ncwd `pwd`\nuser `whoami`\n`echo homedir ~`\nHOME $HOME\n============="
      - name: Checkout commits of each submodule
        run: .github/scripts/check-commit.sh
  tutorial-set-up-check:
    name: tutorial-set-up-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-image:1.0.1
      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - uses: actions/checkout@v2
      - name: fix permissions
        run: sudo chown -R riscvuser .
      - name: Check that the tutorial-setup patches apply
        run: ./scripts/tutorial-setup.sh

  documentation-check:
    name: tutorial-set-up-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-image:1.0.1
      options: --user riscvuser --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - uses: actions/checkout@v2
      - name: fix permissions
        run: sudo chown -R riscvuser .
      - name: Check that documentation builds with no warnings/errors
        run: |
            sudo apt-get update -y
            sudo apt-get install -y python3-pip
            sudo pip3 install -r docs/requirements.txt
            make -C docs html



