name: chipyard-ci-process

on: [push]

env:
  tools-cache-version: v6

jobs:
  cache-test:
    name: cache-test
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fix permissions 1
        run: sudo chown -R riscvuser .
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Hashes
        run: pwd && ls -ltra && .github/scripts/create-hash.sh
      - name: Show hashes
        run: shasum riscv-tools.hash
      - name: generate key
        id: genkey
        run: echo "::set-output name=tools-cache-key::riscv-tools-installed-${{ env.tools-cache-version }}-$(shasum riscv-tools.hash | cut -d' ' -f1)"
      - name: show key
        run: echo ${{ steps.genkey.outputs.tools-cache-key }}
      - uses: actions/cache@v2
        id: riscv-tools-cache
        with:
          path: riscv-tools-install
          key: riscv-tools-install-${{ steps.genkey.outputs.tools-cache-key }}
          restore-keys: riscv-tools-install-${{ steps.genkey.outputs.tools-cache-key }}
      - name: build riscv tools if not cached
        if: steps.riscv-tools-cache.outputs.cache-hit != 'true'
        run: ./.github/scripts/build-toolchains.sh riscv-tools
#        run: |
#          ./.github/scripts/show_fs.sh &
#          ./.github/scripts/build-toolchains.sh riscv-tools
#      - name: Start SSH via Ngrok
#        if: ${{ failure() }}
#        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
#        env:
#          # After sign up on the https://ngrok.com/
#          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
#          # NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
#          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
#
#          # This password you will use when authorizing via SSH
#          # USER_PASS: ${{ secrets.USER_PASS }}
#          USER_PASS: ${{ secrets.USER_PASS }}
#
      - name: What is the filesystem picture
        if: ${{ failure() }}
        run: df -m
#      - name: Don't kill instace
#        if: ${{ failure() }}
#        run: sleep 1h

# Prevent to killing instance after failure
#      - name: check fill
#        run: ls -lt cache-dir

#  use-cache:
#    name: use-cache
#    needs: cache-test
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user root --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - name: step1
#        run: echo step1-${GITHUB_REF}
#      - uses: actions/cache@v2
#        id: cache-222
#        with:
#          path: cache-dir
#          key: cache-dir-${GITHUB_REF}
#          restore-keys: cache-dir-${GITHUB_REF}
#      - name: check fill
#        run: ls -lt cache-dir

#  commit-on-master-check:
#    name: commit-on-master-check
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - name: Hello
#        run: echo =========CHIPYARD CI STARTED=================
#      - name: Dump GitHub context
#        env:
#         GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: fix permissions 1
#        run: sudo chown -R riscvuser .
#      - name: Basics
#        run: whoami && echo pwd `pwd` && ls -la /github ~riscvuser
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: fix permissions 2
#        run: sudo chown -R riscvuser .
#      - name: Check space
#        run: |
#          mkdir -p "/home/riscvuser/riscv-tools"
#          echo ===== df ========
#          df -m
#          echo ===== du . =========
#          df -m .
#          du -s -m .
#          echo ===== du /__w/chipyard/chipyard =========
#          df -m /__w/chipyard/chipyard
#          du -s -m /__w/chipyard/chipyard
#          echo ===== du /home/riscvuser/riscv-tools =========
#          df -m  /home/riscvuser/riscv-tools
#          du -s -m /home/riscvuser/riscv-tools
#          echo ========================
#
#      - name: Banner
#        run: printf "===========Create Hashes\ncwd `pwd`\nuser `whoami`\n`echo homedir ~`\nHOME $HOME\n============="
#      - name: Checkout commits of each submodule
#        run: .github/scripts/check-commit.sh

#  tutorial-set-up-check:
#    name: tutorial-set-up-check
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - uses: actions/checkout@v2
#      - name: fix permissions
#        run: sudo chown -R riscvuser .
#      - name: Check that the tutorial-setup patches apply
#        run: ./scripts/tutorial-setup.sh
#
#  documentation-check:
#    name: tutorial-set-up-check
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#    steps:
#      - uses: actions/checkout@v2
#      - name: fix permissions
#        run: sudo chown -R riscvuser .
#      - name: Check that documentation builds with no warnings/errors
#        run: |
#            sudo apt-get update -y
#            sudo apt-get install -y python3-pip
#            sudo pip3 install -r docs/requirements.txt
#            make -C docs html
#
#  install-riscv-toolchain:
#    name: install-riscv-toolchain
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#      TOOLS_CACHE_VERSION: v6
#    steps:
#      - name: Hello
#        run: echo =========CHIPYARD CI STARTED=================
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: fix permissions 1
#        run: sudo chown -R riscvuser .
#      - name: Basics
#        run: whoami && echo pwd `pwd` && ls -la /github ~riscvuser
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: fix permissions 2
#        run: sudo chown -R riscvuser .
#      - name: Banner
#        run: echo ======CACHE_VERSION===${{ env.TOOLS_CACHE_VERSION }}
#      - name: Set cache dir if not present
#        run: mkdir -p "/home/riscvuser/riscv-tools"
#      - name: Cache Toolchains
#        id: cache-riscv-tools
#        uses: actions/cache@v2
#        with:
#          path: "/home/riscvuser/riscv-tools"
#          key: riscv-tools-installed-${{ env.TOOLS_CACHE_VERSION }}
#          restore-keys: |
#            riscv-tools-installed-${{ env.TOOLS_CACHE_VERSION }}
#            riscv-tools-installed-
#      - name: building
#        if: steps.cache-riscv-tools.outputs.cache-hit != 'true'
#        run: .github/scripts/build-toolchains.sh riscv-tools
#      - name: Check riscv-tools
#        run: ls -ltr /home/riscvuser/riscv-tools
#
#  build-cache:
#    name: build-cache
#    runs-on: ubuntu-latest
#    container:
#      image: ucbbar/chipyard-image:1.0.1
#      options: --user riscvuser --entrypoint /bin/bash
#    env:
#      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
#      TOOLS_CACHE_VERSION: "v6"
#    steps:
#      - uses: actions/checkout@v2
#      - name: fix permissions
#        run: sudo chown -R riscvuser .
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
##      - name: set up cache
##        uses: actions/cache@v2
##        id: chickcache
##        env:
##          cache_name: practice_cache
##        with:
##          path: ./chickdir
##          key: chickdirkey
##          restore-keys: chickdirkey
##      - name: Stuff cache
##        if: steps.chickcache.outputs.cache-hit != 'true'
##        run: mkdir chickdir && echo hellochick > chickdir/chickfile
##      - name: x2
##        run: cat chickdir/chickfile
#
#
#
#
#
#
