name: chipyard-ci-process

on: [push]

env:
  tools-cache-version: v6

jobs:
  install-verilator:
    name: commit-on-master-check
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chipyard-ci-image:ab57b7d
      options: --user root --entrypoint /bin/bash
    env:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
    steps:
      - name: fix permissions
        run: sudo chown -R riscvuser .
      - name: Checkout
        uses: actions/checkout@v2
      - name: testing connection
        uses: appleboy/ssh-action@master
        with:
          host: ferry.millennium.berkeley.edu
          username: circleci
          key: ${{ secrets.PASSWORD }}
          port: 22
          script: hostname && ls -ltr
