name: pactice-actions
on: [push]

jobs:
  test:
    name: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: coursier/cache-action@v5
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
      - name: Mill sanity check
        id: mill
        run: mill __.compile